### ISSUE TITLE
Manual testing between Website and API

### ISSUE THREAD

**Issue by Gnormelli** [kth-ii1302-vt22-group-3/web#17]
# Purpose
This test case is about testing the integration of API into the website. 
Fetch a single object of data from the API and display the values.

# Coverage
- **Scope Type**:
- **Scope Item**: 
- **Coverage**: 

# Input Specifications
- API URL for single object temperature, `http://localhost:3333/temperatures/current`
```sql
INSERT INTO public.temperature (timestamp, value, unit) VALUES ('1970-01-01 00:00:00', 99.9, 'celsius');
```
- Install and develop test code

# Output Specifications
- Display a timestamp of `1970-01-01 00:00:00` and temperature of `99.9`.

# Environmental Needs
- Postgres for the database.
- API repository for running the server.
- Create test for `temperatureView.js` with naming convention `temperatureView.test.js`

# Applicable Releases
# Preconditions
- Installed `jest` dependency and `supertest` dependency.
- Installed `cypress` dependency.

# Postconditions

# Test Procedure
1. STEP 1
2. STEP 2

# Dependencies
Are there any dependencies? If there are any, write their TEST CASE ID and description of why it is a dependency.

# Outcome
## Expected outcome
- Display a timestamp of `1970-01-01 00:00:00` and temperature of `99.9`.

## Evaluation Criteria

**Comment by arifjehoh** [comment]
https://reactjs.org/docs/testing-recipes.html

**Comment by arifjehoh** [comment]
Closing as I need to restructure the test plan
