### ISSUE TITLE
Design website views

### ISSUE THREAD

**Issue by carrogross** [kth-ii1302-vt22-group-3/web#6]

**Comment by carrogross** [comment]
https://lucid.app/lucidchart/b598335f-ba88-4296-a0c7-dd70a579966f/edit?beaconFlowId=C2C8C76613370281&invitationId=inv_499b7a4c-b5be-46cb-8e4d-ad719867c838&page=0_0#

**Comment by carrogross** [comment]
"Must"/"Should" website design + "Could" website design done!

**Comment by arifjehoh** [comment]
Arif Approve!
